# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c39b8a610f603b63008eab9533e294a4b5c65b3446452235f386ad865f13f9ec48ad301c21fd474f0cedbf2dbfbdf46ddb564ec0261fa3f2760c54889648eaed

test:
  secret_key_base: fde2dc82a8bc807f7a80bbdfe612da367bae91305dddf748e907d9dd98dd9414eef75d5ea8f3643e919c1cf071797b75a2218482a26eecd35c7763bf6d691e2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
